### ISSUE TITLE
Managing Donations with BitHub

### ISSUE THREAD

**Issue by liotcheg** [Tox/Tox-Misc#5]
There is a great project BitHub by Open Whisper Systems
https://github.com/WhisperSystems/BitHub
The main idea is that a percentage of bitcoin donations is
automatically paid for every submission to a GitHub repository.

BitHub that does two things:
- Accepts Bitcoin donations and allocates them into a single pool of funds.
- Distributes the Bitcoin donations from that pool to anyone who
commits to specific github repositories.

I believe this is a great solution for the Tox Project.

See this post for more details https://whispersystems.org/blog/bithub/

**Comment by nurupo** [comment]
Thank you for the information, but this is not an appropriate place for this.

Please use other means to communicate in the future, like [IRC or mailing list](https://wiki.tox.chat/users/community).
